# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "VTuber Dictionary"
name: "VTuber Dictionary"
description: "A dictionary to explain common terms in the VTuber community. To live in the rabbit hole, you must learn the rabbit hole.."
menutitlebold: "📘 VTuber Dictionary"
menutitlereg: ""
caption: "To live in the rabbit hole, you must learn the rabbit hole."
baseurl: "/vtuberdictionary"
url: "madekuji.github.io/vtuberdictionary"
color_theme:  "#EE4F87"
color_text:  "#fff"
language:  "en"
socimage: "thumbnail.png"

# Build settings
markdown: kramdown
permalink: /:title/
plugins: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
